Duplicating Data
gristlabs/grist-help pull request #215
Opened 2023-02-01 17:57 UTC by nataliemisasi

adding 'Duplicating Data' section to Raw Data article

2023-02-01 18:50 UTC, anaisconce requested changes
Thank you, Natalie! I made some comments.

2023-02-01 18:50 UTC, anaisconce commented on help/raw-data.md
> +By default, a duplicated table will only contain the table structure, not the data. If you wish to copy all data in addition to the table structure, be sure to check the box prior to clicking 'Save'.
```suggestion
By default, a duplicated table will only contain the table structure, not the data. If you wish to copy all data in addition to the table structure, be sure to check the box prior to clicking 'Save'. If the original table has any access rules, those rules **will not** be duplicated. Only the document's default rules will apply to the copied table.
```

2023-02-01 18:50 UTC, anaisconce commented on help/raw-data.md
> +This will create a new, unlinked duplicate table. Meaning, if you update data in this new copy, the original table will not be updated.
```suggestion
The duplicate table is a new table that is not linked to the original. Meaning, if you update data in the copy, the original table will not be updated, and vice versa.
```

2023-02-01 18:50 UTC, anaisconce commented on help/raw-data.md
> +***insert example as to when you would use this feature***
Oops I think you may have failed to commit some changes. :)

2023-02-01 18:50 UTC, anaisconce commented on help/raw-data.md
> +Note that instead of duplicating tables, it's usually better to segment data using [linked views](linking-widgets.md). For example, if you have multiple clients that all have similar data sets, you c
I'm a bit confused by how the "Client" column segments the data. Also not clear how to segment with linked views. 
 Maybe we can brainstorm a clearer example.

2023-02-01 19:44 UTC, anaisconce requested changes
Thanks! Lastly, `page-widgets.md` also has the `raw-data-nav.png` image. Moving it to another folder broke the link, which is why the test is failing. I think you'll need to fix the image location in the`page-widgets.md` page.

2023-02-01 20:43 UTC, nataliemisasi commented
Notes from discussion: update language around when *not* to use. Remove 'linking widgets' language. 

Example to use: Expenses - rather than having separate tables for each month, include all data in a single table with a new column, month. 

Mention that when you have a lot of similar columns to be used, the data should all be in the same (overlapping columns? make it one table)

No need to include an example as to when you would duplicate a table.

2023-02-08 19:52 UTC, anaisconce approved these changes
🙏

2023-02-08 19:55 UTC, merged