update python version references to 3.11
gristlabs/grist-help pull request #260
Opened 2023-08-18 13:20 UTC by nbush

2023-08-21 16:36 UTC, nataliemisasi requested changes

2023-08-21 16:36 UTC, nataliemisasi commented on help/dates.md
> +objects](https://docs.python.org/3.11/library/datetime.html). That allows
You can use https://docs.python.org/3/library/ instead of specifying the exact version of Python 3 and it will direct to the newest version's library.

2023-08-21 16:36 UTC, nataliemisasi commented on help/python.md
> + * Python 3 (specifically 3.11 at the time of writing)
I think leaving this link that directs specifically to 3.11 is good - since we call out that version specifically. For the rest, I would update to https://docs.python.org/3/library/ then we don't need to update again in the future when our Python version changes.

2023-08-21 21:09 UTC, nataliemisasi requested changes

2023-08-21 21:09 UTC, nataliemisasi commented on help/examples/2020-07-email-compose.md
> +[urllib.parse.quote](https://docs.python.org/3.11/library/urllib.parse.html#urllib.parse.quote).
update to /3/library

2023-08-21 21:09 UTC, nataliemisasi commented on help/examples/2020-09-payroll.md
> +- [max function](https://docs.python.org/3.11/library/functions.html#max):
update to /3/library

2023-08-21 21:09 UTC, nataliemisasi commented on help/formula-cheat-sheet.md
> +in [Python](https://docs.python.org/3.11/library/){:target="\_blank"}, the most popular language for data science. We also have a suite of Excel-like [functions](functions.md), with all-uppercase nam
update to /3/library

2023-08-21 21:09 UTC, nataliemisasi commented on help/formulas.md
> +The entirety of [Python's standard library](https://docs.python.org/3.11/library/) is available
update to /3/library

2023-08-21 21:09 UTC, nataliemisasi commented on help/functions.md
> +In addition, the entire [Python standard library](https://docs.python.org/3.11/library/) is
update to /3/library

2023-08-21 21:09 UTC, nataliemisasi commented on help/python.md
> +The entirety of [Python's standard library](https://docs.python.org/3.11/library/) is available
update to /3/library

2023-08-23 01:06 UTC, nbush reviewed
Done! Not sure how I missed those.

2023-08-23 13:04 UTC, nataliemisasi approved these changes
Looks great!

2023-08-23 13:10 UTC, merged