calendar-widget
gristlabs/grist-help pull request #269
Opened 2023-09-18 20:29 UTC by nataliemisasi

adding support page on calendar widget

2023-09-19 16:07 UTC, nbush commented on help/widget-calendar.md
> +2. [DateTime](col-types.md#datetime-columns) column that will contain the date and time that the event begins.
I think the fix for Date & DateTime support is in (https://gristlabs.getgrist.com/doc/check-ins/p/4#a1.s6.r2769.c19), so this should probably be updated to reflect that.

2023-09-19 16:15 UTC, nbush commented on help/widget-calendar.md
> +The **Calendar** widget allows viewing data in a calendar view. In Grist, event data is stored in a data table. Then, the **Calendar** widget can be configured to display that data.
The current version has several different stylings for "Calendar widget". I think lowercase "calendar widget" makes the most sense, but looking through the other related articles there's a bit of inconsistency (bolded + capitalized in intro paragraph; occasionally capitalized elsewhere).

Similar issue with "Card widget" later on in this article.

2023-09-19 16:18 UTC, nbush commented on help/widget-calendar.md
> +!!! note "Keyboard shortcut"
I'd probably move this after the image.

2023-09-19 16:18 UTC, nbush requested changes
Looks great! A couple tiny change requests.

2023-09-20 20:43 UTC, nbush approved these changes

2023-09-29 13:45 UTC, anaisconce approved these changes

2023-09-29 13:46 UTC, merged