Updating API docs for custom widgets
gristlabs/grist-help pull request #272
Opened 2023-10-10 08:38 UTC by berhalak

- Updating mapping description

2023-10-11 01:21 UTC, georgegevoian requested changes
Thanks @berhalak. Left some suggestions.

2023-10-11 01:21 UTC, georgegevoian commented on help/widget-custom.md
> +-->
Ok to remove this now?
```suggestion
```

2023-10-11 01:21 UTC, georgegevoian commented on help/widget-custom.md
> +options to the `ready` call (see [Widget API](/code/modules/grist_plugin_api/#ready)):
```suggestion
All you need to do is inform Grist that your widget supports linking by passing an additional
option to the `ready` call (see [Widget API](/code/modules/grist_plugin_api/#ready)):
```

2023-10-11 01:21 UTC, georgegevoian commented on help/code/modules/grist_plugin_api.md
> +Now the preferred way it to use ready message.
```suggestion
Now the preferred way is to pass `allowSelectBy` to the ready message.
```

2023-10-11 01:21 UTC, georgegevoian commented on help/code/interfaces/grist_plugin_api.InteractionOptions.md
> +- [theme](grist_plugin_api.InteractionOptions.md#theme)
I'm going to land the diff with the new `ThemeNotifier` shortly. Can you rebase and rebuild the documentation before merging this PR? Hoping to keep this out of the public docs since it's going away.

2023-10-11 01:21 UTC, georgegevoian commented on help/code/interfaces/grist_plugin_api.GristView.md
> +Now the preferred way it to use ready message.
```suggestion
Now the preferred way is to pass `allowSelectBy` to the ready message.
```

2023-10-11 01:21 UTC, georgegevoian commented on help/code/interfaces/grist_plugin_api.ColumnToMap.md
> +Column types (as comma separated list), by default "Any", what means that any type is
```suggestion
Column types (as comma separated list), by default "Any", which means that any type is
```

2023-10-12 08:32 UTC, berhalak commented on help/code/interfaces/grist_plugin_api.ColumnToMap.md
> +Column types (as comma separated list), by default "Any", what means that any type is
Same, a generated, will update in core.

2023-10-17 14:37 UTC, georgegevoian commented on help/code/modules/grist_plugin_api.md
> +- [testWaitForPendingRequests](grist_plugin_api.md#testwaitforpendingrequests)
Sorry, I added this and it should be internal. Let me make a diff that fixes that.

2023-10-18 14:34 UTC, georgegevoian approved these changes
Thanks!

2023-10-18 14:39 UTC, merged