Forms
gristlabs/grist-help pull request #306
Opened 2024-01-24 20:53 UTC by nataliemisasi

new article on forms in Grist 😍

2024-01-24 21:35 UTC, nbush commented on help/images/widget-form/widget-form-default-values.png
should probably update the description in this screenshot as "UI design work in progress" looks a bit weird. i think the current defaults are:
"Form Title"
"Your form description goes here."

2024-01-24 21:36 UTC, nbush commented on help/widget-form.md
> +To add additional form elements, click the + icon at the bottom of the form. From the menu, you can add the following elements;
suggest colon instead of semicolon

2024-01-24 21:38 UTC, nbush commented on help/widget-form.md
> +1. **New Question:** Select a column type to create a new field. `••• More >` will open an expanded menu listing all column types. Adding a new question will add a new column to the underlying data t
`••• More >` to "••• More >"?

2024-01-24 21:38 UTC, nbush commented on help/widget-form.md
> +<center><img src = "/images/widget-form/widget-form-elements.png"></center>
can we do half-size for this image?

2024-01-24 21:43 UTC, nbush commented on help/widget-form.md
> +After you have confirmed everything is as you wish, you can publish your form. Note that only users with OWNER access have permission to publish a form.
suggest "OWNER"

2024-01-24 21:48 UTC, nbush requested changes
minor changes requested, however i think it would be helpful to mention the submission tab on the form widget and its unique features 

<img width="243" alt="image" src="https://github.com/gristlabs/grist-help/assets/3422005/541fcca1-16e0-4d47-8a3c-d6252f4bd5c2">

2024-01-26 14:47 UTC, nataliemisasi commented on help/widget-form.md
> +<center><img src = "/images/widget-form/widget-form-elements.png"></center>
Discussed with Nick via Slack: menu is too small with screenshot-half but too large otherwise. Opted to show menu sections side-by-side

2024-01-26 16:32 UTC, nbush approved these changes

2024-01-26 20:24 UTC, merged