team site and account deletion
gristlabs/grist-help pull request #354
Opened 2024-06-17 20:13 UTC by MichaelNickolas

making changes to billing account image and text... and adding "how do I delete my account" to the FAQ accounts page

2024-06-17 20:49 UTC, nataliemisasi requested changes

2024-06-17 20:49 UTC, nataliemisasi commented on help/en/docs/FAQ.md
> +Alternatively, you can learn more about deleting team sites [here](https://support.getgrist.com/teams/#billing-account).
```suggestion
Need to delete a team site? Learn more [here](https://support.getgrist.com/teams/#billing-account). 
```

2024-06-17 20:49 UTC, nataliemisasi commented on help/en/docs/teams.md
> +You can also delete a team site under Billing Summary by clicking "Delete team site".
Rephrase and make all a single paragraph.

```suggestion
Team sites can be deleted from the Billing Summary page by clicking "Delete team site". Please note that this action cannot be undone and this will remove your site with all documents. Make sure you have created a backup of important data beforehand.
```

Did you test this functionality? What happens if there are team members still assigned to the team, etc?

2024-06-17 20:49 UTC, nataliemisasi commented on help/en/docs/teams.md
> +
```suggestion

```

2024-06-17 20:49 UTC, nataliemisasi commented on help/en/docs/teams.md
> +Please note that this action cannot be undone and this will remove your site with all documents. Make sure you have created a backup of important data beforehand.
```suggestion
```

2024-06-17 21:45 UTC, MichaelNickolas commented on help/en/docs/teams.md
> +<span class="screenshot-large">*![billing account new image](images/billing-account-new-image.png)*</span>
"always name the new image the same as the old image" ... yes, I realized this as I inputted a new image and deleted the old one. But, had already done so, so didn't want to retrace unnecessary steps. 


In terms of my email from the image... noted. Will make the necessary change!

2024-06-18 17:51 UTC, nbush commented on help/en/docs/teams.md
> +<span class="screenshot-large">*![billing account new image](images/billing-account-new-image.png)*</span>
@MichaelNickolas let me know when changes have been made and I'll do a final review.

2024-07-02 14:46 UTC, nbush commented on help/en/docs/FAQ.md
> +You can delete your account in Profile Settings by selecting Delete Account under Privacy & Data. Please note that this action is permanent.
Profile Settings, Delete Account & Privacy & Data should be within quotes. Single quotes according to style guide, though on this page they seem to be all double... maybe we can fix that as well.

2024-07-02 14:48 UTC, nbush commented on help/en/docs/teams.md
> +Team sites can be deleted from the Billing Summary page by clicking "Delete team site". Please note that this action cannot be undone and this will remove your site with all documents. Make sure you
"with all documents" -> "including all documents" is a bit more clear, I think.

2024-07-02 14:49 UTC, nbush requested changes
Some small formatting things but otherwise good to go.

2024-07-03 17:54 UTC, nbush reviewed
This is very annoying, but there are still a few double quotes in FAQ.md and team-sharing.md if we want to update them now... If you want to do that we're good to merge!

2024-07-03 20:04 UTC, nbush approved these changes
Funnily enough my review found that this line in FAQ.md doesn't close its quotes!

`<iframe src="https://templates.getgrist.com/6D8E2h2DQNwS/Task-Management/p/6?embed=true></iframe>`

Otherwise this is good to merge!

2024-07-03 20:50 UTC, merged