applying styling changes based on Grist styling guide
gristlabs/grist-help pull request #362
Opened 2024-07-15 15:27 UTC by nataliemisasi

2024-08-01 20:05 UTC, nbush commented on help/en/docs/col-refs.md
> +To filter a reference column’s dropdown list, select the reference column then 'Set dropdown condition` in the *creator panel* under the 'Column' tab.
Closing backtick ` instead of '.

2024-08-01 20:27 UTC, nbush commented on help/en/docs/col-refs.md
> +You can filter a dropdown’s choice by writing a condition as a formula. The attribute `choice` refers to choices in the dropdown. In this case the formula is `choice.Country_Cities == $Country_Pop_Ra
I feel like this is where it gets a bit confusing for me, because I have no idea of the structure of the overall document. I fear the colons make the confusion a worse, as they are kind of pseudo-hierarchical and get removed when put in a formula.

A drastic suggestion if you think it may help:
1. Drop the population ranking framing
2. Two tables, Filtered Cities & Raw Cities (or similar)
3. In Raw Cities, have **Country** and **City** columns
4. In Population Rankings, have **Filter Country** and then just **Filtered City**

In this case the formula should be `choice.Country == $Filter_Country`, which should hopefully eliminate the ambiguity, unless I've screwed something up.

2024-08-01 20:28 UTC, nbush requested changes
One somewhat major suggestion that I think might help simplify things, but open to other ideas.

2024-08-15 14:52 UTC, nbush requested changes
One final request to add a link to the Country/City doc in the opening paragraph of the section to show the reference structure.

2024-08-19 14:32 UTC, jr-grist requested changes
Explain structure of tables in example before diving into the formula and introducing choice.Country

2024-09-04 15:35 UTC, nataliemisasi commented
merging to add current changes. Jordan will create a separate PR to add link and further explanation

2024-09-04 15:35 UTC, merged