webhooks: add initial documentation
gristlabs/grist-help pull request #365
Opened 2024-07-22 21:25 UTC by jordigh

2024-07-24 12:59 UTC, Spoffy reviewed
Looks good to me, I learned a lot about how our webhooks work! :grin: 

That said, I'm also not familiar with them, so wouldn't be able to tell if anything was missing!

The only thing I'm wondering is if it's worth talking about how reference types are handled? The normal Grist API gives unusual arrays of IDs, rather than resolving and expanding the reference. Not sure if webhooks do the same, or if it's worth talking about.

Overall, really easy to read docs :slightly_smiling_face:

2024-07-24 12:59 UTC, Spoffy commented on help/en/docs/webhooks.md
> +manage rows to a table.
> Conceptually, this is similar to the card widget used to manage rows to a table

Having this here caused me a little confusion as I figured out what it was referring to (admittedly the screenshots don't show in PR review!). I'm not sure if this would be better without this sentence, what do you think?

2024-07-24 12:59 UTC, Spoffy approved these changes

2024-07-24 18:12 UTC, nataliemisasi requested changes
Some formatting changes per our [Grist Content Style Guide](https://grist.quip.com/ei5kAlQZxj7M/Grist-Content-Style-Guide).

2024-07-24 18:12 UTC, nataliemisasi commented on help/en/docs/webhooks.md
> +"clear queue" in the webhook's configuration page will remove any
```suggestion
'Clear Queue' button in the webhook's configuration page will remove any
```

2024-07-24 18:12 UTC, nataliemisasi commented on help/en/docs/webhooks.md
> +
```suggestion
```

No need for a table of contents. The left-hand nav panel already includes this. We can start with the title `# Webhooks` and then jump into `Webhooks enable you to...`.

2024-07-24 18:12 UTC, nataliemisasi commented on help/en/docs/webhooks.md
> +"Manage Webhooks" button.
```suggestion
Under the 'API' section of 'Document Settings', click on the
'Manage Webhooks' button.
```

2024-07-24 18:12 UTC, nataliemisasi commented on help/en/docs/webhooks.md
> +Column" in the webhook's configuration can be useful for gating which
```suggestion
case, those rows will be sent together in the same payload. The 'Ready
Column' in the webhook's configuration can be useful for gating which
```

2024-07-24 18:12 UTC, nataliemisasi commented on help/en/docs/webhooks.md
> +will keep retrying periodically. The "Status" column in the webhook
```suggestion
will keep retrying periodically. The 'Status' column in the webhook
```

2024-07-24 20:50 UTC, jordigh commented on help/en/docs/webhooks.md
> +manage rows to a table.
You're right, it's better without. I've removed that sentence.

2024-07-24 20:56 UTC, jordigh commented on help/en/docs/webhooks.md
> +![webhooks-settings](images/webhooks/settings.png)
Okay, done!

2024-07-30 20:46 UTC, georgegevoian commented on help/en/docs/webhooks.md
> +<center>![webhooks-settings](images/webhooks/settings.png)</center>
The image is a little big now that it's using a 2x version. Could you try shrinking it to half-width? (There's a class you can set - `.screenshot-half` - that appears frequently in the other files.)

2024-07-30 22:43 UTC, jordigh commented on help/en/docs/webhooks.md
> +<center>![webhooks-settings](images/webhooks/settings.png)</center>
Okay, done.

2024-07-31 14:59 UTC, georgegevoian approved these changes
Looks great. Thanks!

2024-07-31 16:22 UTC, merged