Two-Way References
gristlabs/grist-help pull request #426
Opened 2024-09-25 19:27 UTC by nataliemisasi

adding two-way-reference section to Reference columns article

2024-09-25 21:07 UTC, jr-grist approved these changes
Added more clear language to distinguish between 'reference column' and 'reverse reference column'

2024-09-25 21:07 UTC, jr-grist commented on help/en/docs/col-refs.md
> +By default, new reference columns are created as a one-way reference, meaning that the reference is only shown in a single column in the table you have added it in. Grist also allows you to configure
```suggestion
By default, new reference columns are created as one-way references, meaning that the references are only shown in a single column in the table you have added it in. Grist also allows you to configure a reference column with two-way references, meaning that the references will be shown in the column you initially added in the source table and in a reverse reference column in the referenced table.
```

2024-09-25 21:07 UTC, jr-grist commented on help/en/docs/col-refs.md
> +This creates a reference column in the referenced table, *Clients*. Because there could be multiple projects for a single client, the **Projects** column is a [Reference List](col-types.md#reference-
```suggestion
This creates a reverse reference column in the referenced table, *Clients*. Because there could be multiple projects for a single client, the **Projects** column is a [Reference List](col-types.md#reference-list-columns). An update made in a reference column will be reflected in the corresponding reverse reference column.
```

2024-09-26 16:27 UTC, nbush requested changes
This is a concise summary of the feature, and I think fine to release in its current state pending your review of my changes. I made some updates based on the language used in the UI to help keep things consistent (omitting "reverse", using "target" for example).

There are a few fringe elements that are still undocumented:
1. The "Record already assigned" warning you get when trying to add references to multiple records where that is not allowed (i.e. not a RefList).
2. The (somewhat unintuitive) behaviour when deleting a two-way reference (it also deletes a column)
3. The note that you can't use two-way references on Formula columns

I don't think these are critical for now, but are probably worth documenting at some point.

2024-09-26 16:34 UTC, nataliemisasi commented
reviewed nick's changes. they look good

2024-09-26 16:41 UTC, nbush approved these changes
Follow-up task created.

2024-09-26 16:41 UTC, merged