Added ex. showing how to reorder conditional rules
gristlabs/grist-help pull request #431
Opened 2024-10-10 14:54 UTC by jr-grist

Added text and animation showing how to drag-and-drop conditional rules into a new order

2024-10-10 16:08 UTC, nbush commented on help/en/docs/conditional-formatting.md
> +Note that Grist applies the rules in order. Styles applied by later rules will override those applied by earlier rules. To change the order of the rules, click and drag the appropriate rule to its ne
I know the animation shows it, but it's really disorienting for it to say "drag handles" here but them be invisible in the screenshot immediately after. I think we need something like:
> To change the order of the rules, click and drag the appropriate rule to its new position using the drag handles to the left of each rule. Note: These handles only appear once you hover over each rule.

That's a bit chunky, but I think it should be called out somewhere.

2024-10-10 16:08 UTC, nbush requested changes
Small clarification requested.

2024-10-16 12:31 UTC, nataliemisasi requested changes

2024-10-16 12:31 UTC, nataliemisasi commented on help/en/docs/conditional-formatting.md
> -Note that Grist applies the rules in order. Styles applied by later rules will override those applied by earlier rules.
What does this mean? Specify that the order is top to bottom

2024-10-16 12:31 UTC, nataliemisasi commented on help/en/docs/conditional-formatting.md
> +Note that Grist applies the rules in order. Styles applied by later rules will override those applied by earlier rules. To change the order of the rules, click and drag the appropriate rule to its ne
You could also include a small screenshot right after this paragraph that includes the two vertical bars.
![image](https://github.com/user-attachments/assets/5569b85e-8f12-408a-aa93-9cc5c5bfb2e1)

2024-10-23 11:43 UTC, jr-grist reviewed
Addressed comments re: clarifying list order, context for drag handles

2024-10-23 11:43 UTC, jr-grist commented on help/en/docs/conditional-formatting.md
> +Note that Grist applies the rules in order. Styles applied by later rules will override those applied by earlier rules. To change the order of the rules, click and drag the appropriate rule to its ne
```suggestion
Note that Grist applies the rules in order from top to bottom. Styles applied by rules that appear later in the list will override those applied by rules earlier in the list. To change the order of the rules, hover over a rule to reveal a drag handle, then click and drag the drag handle to move the rule to its new position.
```

2024-10-23 11:43 UTC, jr-grist commented on help/en/docs/conditional-formatting.md
> -Note that Grist applies the rules in order. Styles applied by later rules will override those applied by earlier rules.
See suggestion on Nick's comment below for resolution

2024-10-23 11:43 UTC, jr-grist commented on help/en/docs/conditional-formatting.md
> +Note that Grist applies the rules in order. Styles applied by later rules will override those applied by earlier rules. To change the order of the rules, click and drag the appropriate rule to its ne
I think a text-based solution is preferable to including another screenshot, but I can go that route if this still isn't clear

2024-10-23 20:18 UTC, nbush commented on help/en/docs/conditional-formatting.md
> +Note that Grist applies the rules in order. Styles applied by later rules will override those applied by earlier rules. To change the order of the rules, click and drag the appropriate rule to its ne
One last suggestion to remove the extra "drag": "hover over a rule to reveal a drag handle, then click and drag the drag handle" -> "hover over a rule to reveal a drag handle, then click and drag the handle"

Otherwise the above commit is good!

2024-10-23 20:19 UTC, nbush requested changes
One more tiny change.

2024-10-23 20:20 UTC, nataliemisasi commented on help/en/docs/conditional-formatting.md
> +Note that Grist applies the rules in order. Styles applied by later rules will override those applied by earlier rules. To change the order of the rules, click and drag the appropriate rule to its ne
I agree with Nick

2024-10-23 20:21 UTC, nataliemisasi requested changes
See Nick's comment about "drag". Otherwise, looks good 👍

2024-10-24 15:54 UTC, nataliemisasi approved these changes
Looks good, thanks!

2024-10-24 15:55 UTC, merged