Document SCIM
gristlabs/grist-help pull request #434
Opened 2024-10-18 19:19 UTC by fflorent

See this PR for the implementation: https://github.com/gristlabs/grist-core/pull/1199

2024-11-29 17:25 UTC, jordigh commented on help/en/docs/install/scim.md
> +### **The Role of OIDC or SAML**
Wow, this section really does read like AI slop. But I guess it's useful slop, so might as well keep it.

2024-11-29 17:29 UTC, fflorent commented on help/en/docs/install/scim.md
> +### **The Role of OIDC or SAML**
Yeah, that's exactly that part which has been generated by GPT as mentioned in the PR description 😅

2024-11-29 23:27 UTC, paulfitz commented on help/en/docs/install/scim.md
> +### **The Role of OIDC or SAML**
Would it be possible to link to some trusted external reference for context instead?

2024-11-30 13:39 UTC, fflorent commented on help/en/docs/install/scim.md
> +### **The Role of OIDC or SAML**
I would feel more comfortable with rephrasing with my own words than just simply linking to some reference (I still may add them).

2024-12-01 16:01 UTC, fflorent commented on help/en/docs/install/scim.md
> +### **The Role of OIDC or SAML**
I have rephrased to make these paragraphs more concise, though with no external references, if that's fine for you

2024-12-02 16:57 UTC, nbush commented on help/en/docs/install/scim.md
> +!!! warning "🚧 Status of SCIM"
I would move this to the top of the page.

Also should it not be "group management" instead of "the groups management"?

2024-12-02 17:01 UTC, nbush commented on help/en/docs/install/scim.md
> +- **Provision** and **deprovision** users as soon as they respectively enter or leave your organization.
Revision:
Provisioning and deprovisioning users as soon as they enter or leave your organization, respectively.

2024-12-02 17:02 UTC, nbush commented on help/en/docs/install/scim.md
> +- Updating your users information.
Missing apostrophe: "users'"

2024-12-02 17:03 UTC, nbush commented on help/en/docs/install/scim.md
> +- `GRIST_ENABLE_SCIM`: set its value to `true` so you enable the SCIM endpoints;
replace semicolon with period

2024-12-02 17:12 UTC, nbush commented on help/en/docs/install/scim.md
> +This is for all of the tasks mentioned above where **SCIM** intervene. When you operate changes on your users and your groups on an Identity Provider which includes a SCIM client, it will automatical
These two paragraphs are really hard for me to parse. Suggested revision:

> For example, when you make changes to users or user groups in an identity provider, SCIM will automatically propagate those changes across every service provider (i.e. Grist) that supports the SCIM API.
>
> Also, SCIM allows you to deprovision users as soon as they leave. This ensures that they cannot log in without waiting their sessions to expire, which is a step toward complying with the GDPR if your organization is based in Europe.

One thing I'm not sure about is what an "identity provider" is exactly. Is it always a client? Can we include an example like "(i.e. OIDC)"?

2024-12-02 17:13 UTC, nbush requested changes
Some technical questions, suggestions, and style notes.

2024-12-02 22:08 UTC, jordigh commented on help/en/docs/install/scim.md
> +This is for all of the tasks mentioned above where **SCIM** intervene. When you operate changes on your users and your groups on an Identity Provider which includes a SCIM client, it will automatical
The identity provider is a bit of OIDC jargon. It's the service you connect with Grist (in our case) in order to log in your users, so e.g. Google or Microsoft logins are possible identity providers.

2024-12-06 09:30 UTC, fflorent commented on help/en/docs/install/scim.md
> +This is for all of the tasks mentioned above where **SCIM** intervene. When you operate changes on your users and your groups on an Identity Provider which includes a SCIM client, it will automatical
@nbush Thanks for your suggestion. I rephrased the two paragraph, keeping the `This is for all of the tasks mentioned above where SCIM intervene.`. Or does it also troubles you?

2024-12-06 16:58 UTC, fflorent commented
@nbush Your remarks has been taken into account, thanks for your review!

2024-12-06 19:54 UTC, nbush commented on help/en/docs/install/scim.md
> +This is for all of the tasks mentioned above where **SCIM** intervene. When you operate changes on your users and your groups on an Identity Provider which includes a SCIM client, it will automatical
I'm actually not really sure what `This is for all of the tasks mentioned above where SCIM intervene.` is supposed to mean. 😓 It's not clear what "this" refers to, and "intervene" feels like an odd verb here. Would you be able to rephrase?

2024-12-06 19:55 UTC, nbush commented on help/en/docs/install/scim.md
> +### **The Role of OIDC or SAML**
@fflorent Would you be able to update the other subheadings as well?

2024-12-06 19:56 UTC, nbush requested changes
A few minor changes left, otherwise good to go!

2024-12-14 14:48 UTC, fflorent commented on help/en/docs/install/scim.md
> +### **The Role of OIDC or SAML**
Ah right, you mean capitalize only the first letter. I am doing that!

2024-12-14 14:52 UTC, fflorent commented on help/en/docs/install/scim.md
> +This is for all of the tasks mentioned above where **SCIM** intervene. When you operate changes on your users and your groups on an Identity Provider which includes a SCIM client, it will automatical
Sorry, that's a bad translation of what I meant. Is this better?

2024-12-14 14:53 UTC, fflorent commented
@nbush I applied some changes, is it good this time?

2024-12-16 19:28 UTC, merged

2024-12-17 13:16 UTC, paulfitz commented
@fflorent there's a report from @dsagal of api console trouble, wondering if related to the yml change here
![Screenshot 2024-12-17 at 00 38 13](https://github.com/user-attachments/assets/2f2f7bef-28ca-4961-ae43-ec7cfaf9aa9d)

2024-12-17 13:25 UTC, fflorent commented
@paulfitz I propose you this PR to revert the SCIM documentation: #457 . As a temporary fix.

I will then fix that properly ASAP.