marketplace: write instructions for transitioning
gristlabs/grist-help pull request #447
Opened 2024-11-23 00:06 UTC by jordigh

There are very few users who should ever need to do this, so the instructions are a little sparse on details. I believe this to be an acceptable compromise.

2024-11-25 20:09 UTC, paulfitz reviewed
With a few more details to help the user's mental model in case of problems (and there are always problems), this is close to fine. I was hoping for instructions that would help with transitioning any single-server setup, with some extra notes for AWS-specific steps, but maybe there isn't enough to say.

The main thing I'd like to see fleshed out is to systematically clue the user in on the default email wrinkle. It is dangerous and confusing to be setting up Grist without knowing what that is about. Feels like it merits a section in the self-managed handbook, rather than a very passing mention in telemetry which is all I see right now? https://support.getgrist.com/self-managed/#how-do-i-control-telemetry

It would be super helpful if you told users that this email will control access to the single team site that gets created for them on first run, and the consequences and symptoms of changing it. And that'll be valuable not only for AWS users but lots of other people.

2024-11-25 20:09 UTC, paulfitz commented on help/en/docs/install/aws-marketplace-transition.md
> +3. Follow [the instructions to run the bootstrap script](https://github.com/gristlabs/grist-pack/tree/main/dist#quickstart) , using the value of `EMAIL` for the `DEFAULT_EMAIL` value. You do not need
(excess space in front of comma?)

It would be good to either link to some explanation of the role of this setting (adding it elsewhere if necessary), or include such an explanation in place. Otherwise it could be difficult for the user if there are any problems to know whether it had the desired effect or not.

2024-11-25 20:09 UTC, paulfitz commented on help/en/docs/install/aws-marketplace-transition.md
> +The traditional method to copy files across instances is `scp`, a file transfer mechanism over the SSH protocol. A small complication is that the user to copy-to, `grist` in the target EC2 instance,
hyphen not needed in `copy-to`?

2024-11-25 22:46 UTC, jordigh commented on help/en/docs/install/aws-marketplace-transition.md
> +The traditional method to copy files across instances is `scp`, a file transfer mechanism over the SSH protocol. A small complication is that the user to copy-to, `grist` in the target EC2 instance,
Not sure why that hyphen seemed correct to me. I've removed it.

2024-11-25 22:47 UTC, jordigh commented on help/en/docs/install/aws-marketplace-transition.md
> +There are a couple of standard methods to copy files across EC2 instances.
Added a comment about this.

2024-11-26 19:59 UTC, jordigh commented on help/en/docs/install/aws-marketplace-transition.md
> +3. Follow [the instructions to run the bootstrap script](https://github.com/gristlabs/grist-pack/tree/main/dist#quickstart) , using the value of `EMAIL` for the `DEFAULT_EMAIL` value. You do not need
I've added a reference that should explain what this default email variable should do.

2024-11-26 20:20 UTC, nbush commented on help/en/docs/install/aws-marketplace-transition.md
> +store?"](../../self-managed#what-files-does-grist-storex) for an
extra "x" on the

2024-11-26 20:21 UTC, nbush commented on help/en/docs/install/aws-marketplace-transition.md
> +does not have ssh login enabled. We recommend copying into the default
"an SSH login" or "an `ssh` login"?

2024-11-26 20:22 UTC, nbush requested changes
a couple tiny things

2024-11-26 20:51 UTC, merged