Document SCIM again
gristlabs/grist-help pull request #458
Opened 2024-12-17 17:15 UTC by fflorent

Restore #434 fixing the issue with the SCIM API yaml.

2024-12-18 10:18 UTC, hexaltation requested changes
Just a nitpick in ENV variables descriptions

2024-12-18 10:23 UTC, fflorent commented on help/en/docs/install/scim.md
> +- `GRIST_SCIM_USER`: (optional) give this variable the email address of an account to give it access to the SCIM endpoints.
I don't agree, we should say `give [someone/something] access`. It's [distransitive](https://en.wiktionary.org/wiki/Appendix:Glossary#ditransitive) ([source](https://en.wiktionary.org/wiki/give))

2024-12-19 13:21 UTC, fflorent commented on help/en/docs/install/scim.md
> +- `GRIST_SCIM_USER`: (optional) give this variable the email address of an account to give it access to the SCIM endpoints.
Also the wiktionary gives the example of the `give` verb for the ditransitivity:

> (of a verb) taking two objects, such as [give](https://en.wiktionary.org/wiki/give#English) in “Give me the ball” (where [me](https://en.wiktionary.org/wiki/me#English) is an [indirect object](https://en.wiktionary.org/wiki/Appendix:Glossary#indirect_object) and [the ball](https://en.wiktionary.org/wiki/ball#English) is a [direct object](https://en.wiktionary.org/wiki/Appendix:Glossary#direct_object)). Compare [intransitive](https://en.wiktionary.org/wiki/Appendix:Glossary#intransitive_verb), [transitive](https://en.wiktionary.org/wiki/Appendix:Glossary#transitive_verb), and [ambitransitive](https://en.wiktionary.org/wiki/Appendix:Glossary#ambitransitive_verb) verbs.

2024-12-19 15:56 UTC, jonathanperret commented on help/en/docs/install/scim.md
> +The SCIM implementation is documented in the [Grist Rest API reference](/api/#tag/scim).
```suggestion
The SCIM implementation is documented in the [Grist REST API reference](/api/#tag/scim).
```

2024-12-19 15:58 UTC, fflorent commented on help/en/docs/install/scim.md
> +
Maybe explain that you can then use the endpoint by using the API key associated with the account above?

2024-12-19 16:01 UTC, fflorent commented on api/scim/users.yml
> +        - users
Remove the `users` tag. Makes everything redundant in the API documentation.

2024-12-19 16:02 UTC, fflorent commented on api/scim/users.yml
> +        - users
Also add the endpoint so it is referenced in the left menu
![image](https://github.com/user-attachments/assets/36ced0f5-349e-4e62-9548-5bb70d68d493)

2024-12-20 19:37 UTC, hexaltation approved these changes
LGTM 🎅

2024-12-20 21:25 UTC, merged

2024-12-20 21:28 UTC, fflorent commented
Thank you @hexaltation!