clarify interpretation of less and greater as before/after
gristlabs/grist-help pull request #461
Opened 2024-12-22 05:49 UTC by combinatorist

I welcome edits / rephrasing. This is just the simplest change to make it clear to me, but it might only muddle it for others.

2024-12-25 23:29 UTC, dsagal commented on help/en/docs/functions.md
> +- __`le`__: (less than or equal to) find nearest record with sort values <= (last before or first equal) the given values
I think it should actually be "last that's before or equal" -- if you have multiple equal values to the one you are looking up, it should return the last of these.

2024-12-25 23:29 UTC, dsagal commented on help/en/docs/functions.md
> +- __`ge`__: (greater than or equal to) find nearest (first) record with sort values >= (equal or after) the given values
this one should be "first equal or after", though I think this is clear as is. Maybe `le` can be phrased the same way.

2025-01-16 21:39 UTC, combinatorist commented on help/en/docs/functions.md
> +- __`le`__: (less than or equal to) find nearest record with sort values <= (last before or first equal) the given values
Feel free to edit this PR to so the phrasing is more accurate. I was just pointing out that it wasn't clear to without these details. If it feels cleaner to you, maybe you could these alternative explanations somewhere else and link to that.

2025-01-30 04:26 UTC, dsagal commented
Sorry to be slow. I think the extra explanation paragraph you added clarifies things nicely, so I simplified a bit the editing of the individual methods. If it looks good to you, I'll merge in. Preview here: https://deploy-preview-461--grist-help-preview.netlify.app/functions/#find_

2025-01-30 18:54 UTC, nataliemisasi requested changes
Made some updates to the formatting (capitalization, punctuation) to match formatting of list found here: https://deploy-preview-461--grist-help-preview.netlify.app/functions/#datedif

Added filler words because the existing phrasing requires the reader to mentally fill in gaps, making it harder to process. Since the concept is already a bit complex, including these filler words makes it easier to understand at a glance.

2025-01-30 18:54 UTC, nataliemisasi commented on help/en/docs/functions.md
> +- __`eq`__: ("equal to") find the first record with sort values equal to the given values
```suggestion
- __`lt`__: ("less than") Finds the nearest (last) record where the sort values are **before** the given values.
- __`le`__: ("less than or equal to") Finds the last record where the sort values are **equal to or before**
  the given values.
- __`gt`__: ("greater than") Finds the nearest (first) record where the sort values are **after** the given values.
- __`ge`__: ("greater than or equal to") Finds the first record where the sort values are **equal to or after**
  the given values.
- __`eq`__: ("equal to") Finds the first record where the sort values are **equal to** the given values.
```

2025-01-31 03:28 UTC, dsagal commented on help/en/docs/functions.md
> +- __`eq`__: ("equal to") find the first record with sort values equal to the given values
Done, thank you!

2025-02-11 16:46 UTC, nataliemisasi approved these changes

2025-02-11 16:52 UTC, merged